from app.models import db, Car

def seed_cars():
  cars = [
  {
    "seller_id": 1,
    "year": 2023,
    "make": "Chevrolet",
    "model": "Camaro",
    "trim": "3LT",
    "miles": 5,
    "price": 48485,
    "condition": "Excellent",
    "new": True,
    "ex_color": "White",
    "in_color": "Tan",
    "drivetrain": "Rear-wheel Drive",
    "mpg": 26,
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "engine": "3.6L V6 GDI DOHC"
  },
  {
    "seller_id": 1,
    "year": 2018,
    "make": "Chevrolet",
    "model": "Camaro",
    "trim": "2LT",
    "miles": 47354,
    "price": 31800,
    "condition": "Good",
    "new": False,
    "ex_color": "Black",
    "in_color": "Black",
    "drivetrain": "Rear-wheel Drive",
    "mpg": 24,
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "engine": "V6 Cylinder Engine"
  },
  {
    "seller_id": 1,
    "year": 2018,
    "make": "Chevrolet",
    "model": "Camaro",
    "trim": "ZL1",
    "miles": 40179,
    "price": 58977,
    "condition": "Good",
    "new": False,
    "ex_color": "Red",
    "in_color": "Grey",
    "drivetrain": "Rear-wheel Drive",
    "mpg": 17,
    "fuel_type": "Gasoline",
    "transmission": "Manual",
    "engine": "6.2L V8 16V GDI OHV Supercharged"
  },
  {
    "seller_id": 1,
    "year": 2018,
    "make": "Chevrolet",
    "model": "Malibu",
    "trim": "LT",
    "miles": 40317,
    "price": 21350,
    "condition": "Good",
    "new": False,
    "ex_color": "Red",
    "in_color": "Black",
    "drivetrain": "Front-wheel Drive",
    "mpg": 34,
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "engine": "1.5L I4 16V GDI DOHC Turbo"
  },
  {
    "seller_id": 1,
    "year": 2018,
    "make": "Chevrolet",
    "model": "Malibu",
    "trim": "LT",
    "miles": 96200,
    "price": 17900,
    "condition": "Fair",
    "new": False,
    "ex_color": "Black",
    "in_color": "Black",
    "drivetrain": "Front-wheel Drive",
    "mpg": 34,
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "engine": "1.5L I4 16V GDI DOHC Turbo"
  },
  {
    "seller_id": 2,
    "year": 2018,
    "make": "Honda",
    "model": "CR-V",
    "trim": "EX-L",
    "miles": 44689,
    "price": 26405,
    "condition": "Excellent",
    "new": False,
    "ex_color": "Silver",
    "in_color": "Black",
    "drivetrain": "Front-wheel Drive",
    "mpg": 32,
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "engine": "1.5L I4 16V GDI DOHC Turbo"
  },
  {
    "seller_id": 2,
    "year": 2019,
    "make": "Honda",
    "model": "CR-V",
    "trim": "EX",
    "miles": 42198,
    "price": 28700,
    "condition": "Excellent",
    "new": False,
    "ex_color": "White",
    "in_color": "Black",
    "drivetrain": "All-wheel Drive",
    "mpg": 33,
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "engine": "1.5L I4 16V GDI DOHC Turbo"
  },
  {
    "seller_id": 2,
    "year": 2022,
    "make": "Honda",
    "model": "CR-V",
    "trim": "EX-L",
    "miles": 11,
    "price": 35040,
    "condition": "Excellent",
    "new": True,
    "ex_color": "White",
    "in_color": "Tan",
    "drivetrain": "All-wheel Drive",
    "mpg": 32,
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "engine": "1.5L I4 16V GDI DOHC Turbo"
  },
  {
    "seller_id": 3,
    "year": 2007,
    "make": "Honda",
    "model": "Civic",
    "trim": "LX",
    "miles": 220449,
    "price": 5998,
    "condition": "Poor",
    "new": False,
    "ex_color": "White",
    "in_color": "Tan",
    "drivetrain": "Front-wheel Drive",
    "mpg": 30,
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "engine": "1.8L I4 16V MPFI SOHC"
  },
  {
    "seller_id": 3,
    "year": 2015,
    "make": "Honda",
    "model": "Civic",
    "trim": "LX",
    "miles": 11390,
    "price": 14994,
    "condition": "Poor",
    "new": False,
    "ex_color": "White",
    "in_color": "Grey",
    "drivetrain": "Front-wheel Drive",
    "mpg": 36,
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "engine": "1.8L I4 16V MPFI SOHC"
  }]

  for car in cars:
    new_car = Car(
      seller_id = car["seller_id"],
      year = car["year"],
      make = car["make"],
      model = car["model"],
      trim = car["trim"],
      miles = car["miles"],
      price = car["price"],
      condition = car["condition"],
      new = car["new"],
      ex_color = car["ex_color"],
      in_color = car["in_color"],
      drivetrain = car["drivetrain"],
      mpg = car["mpg"],
      fuel_type = car["fuel_type"],
      transmission = car["transmission"],
      engine = car["engine"]
    )

    db.session.add(new_car)

  db.session.commit()
  print('\n')
  print('Cars were successfully seeded')
  print('\n')

def undo_cars():
    db.session.execute('TRUNCATE cars RESTART IDENTITY CASCADE;')
    db.session.commit()
